#
# fly.toml app configuration template file
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "node-react-ts-demo"
primary_region = "cdg"

[build]

  dockerfile = "../app/Dockerfile"

    [build.args]
    NODE_VERSION = "18.17.1"
    NPM_VERSION = "9.8.1"

[env]

  AUTH_PASSWORD = "MyBigSecret"
  AUTH_USERNAME = "johndoe"
  COOKIE_SECRET = "MyBigSecret"
  CORS_ORIGIN = "https://node-react-ts-demo.headwood.giize.com"
  HOST = "0.0.0.0"
  JWT_SECRET = "MyBigSecret"
  LOG_LEVEL = "debug"
  PORT = 3000

[http_service]

  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

  [[http_service.checks]]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    timeout = "5s"
    path = "/health"
